version: "3.3"

services:
  # klassez-db:
  #   build: ./backend/mysql
  #   restart: always
  #   ports:
  #     # <Port exposed> : <MySQL Port running inside container>
  #     - '3306:3306'
  #   expose:
  #     - '3306'
  #   volumes:
  #     - klassez-vol:/var/lib/mysql
  #   networks:
  #     - klassez-net

  backend-api:
    build: ./backend
    restart: always
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "yarn && yarn run dev"
    ports:
      - 8000:8000
    networks:
      - klassez-net

  frontend-app:
    # image: node:12
    tty: true
    build: ./frontend
    restart: always
    working_dir: /usr/src/app
    command: bash -c "yarn && yarn start"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend-api
    ports:
      - 3000:3000
    networks:
      - klassez-net

# we are using a network to connect these
# two containers. They will be part of the same virtual network
# called 'backend'.
networks:
  klassez-net: